{
 "title": "QE Dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 } },
  { "title": "Dynamic VMs (Server)", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 4, "y": 0 } },
  { "title": "Dynamic VMs (Mobile)", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 0 } },
  { "title": "Static VMs", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 } },
  { "title": "Windows", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 4, "y": 1 } },
  { "title": "Linux", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 8, "y": 1 } },
  {
   "title": "Busy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "mobile_active_vms_windows", "type": "table" },
    { "target": "mobile_active_vms_linux", "type": "table" }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "mobile_available_vms_windows", "type": "table" },
    { "target": "mobile_available_vms_centos", "type": "table" }
   ]
  },
  {
   "title": "Busy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "total_busy_vms" }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "total_available_vms" }
   ]
  },
  {
   "title": "Busy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "active_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "available_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "Busy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "active_vms_linux", "type": "table" }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "available_vms_centos", "type": "table" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "available_vms_windows", "type": "table" },
    { "target": "available_vms_centos", "type": "table" },
    { "target": "active_vms_linux", "type": "table" },
    { "target": "active_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "mobile_available_vms_windows", "type": "table" },
    { "target": "mobile_available_vms_centos", "type": "table" },
    { "target": "mobile_active_vms_linux", "type": "table" },
    { "target": "mobile_active_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "total_available_vms" },
    { "expr": "total_busy_vms" }
   ]
  }
 ]
}