{
 "title": "Server Dynamic VMs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Active VMs (Windows)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "active_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "Available VMs (Windows)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "available_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "Active VMs (Linux)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "active_vms_linux", "type": "table" }
   ]
  },
  {
   "title": "Available VMs (Centos)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "available_vms_centos", "type": "table" }
   ]
  },
  {
   "title": "Daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "compute_hours_daily", "type": "timeseries" },
    { "target": "vms_created_daily", "type": "timeseries" }
   ]
  },
  {
   "title": "Weekly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "compute_hours_weekly", "type": "timeseries" },
    { "target": "vms_created_weekly", "type": "timeseries" }
   ]
  },
  {
   "title": "Monthly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "compute_hours_monthly", "type": "timeseries" },
    { "target": "vms_created_monthly", "type": "timeseries" }
   ]
  },
  { "title": "Today", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 13 } },
  { "title": "This Week", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 13 } },
  { "title": "This Month", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 13 } },
  {
   "title": "Compute Hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "compute_hours_daily", "type": "timeseries" }
   ]
  },
  {
   "title": "Max Hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "available_vms_windows", "type": "table" },
    { "target": "active_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "VMs Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "vms_created_daily", "type": "timeseries" }
   ]
  },
  {
   "title": "Compute Hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "compute_hours_weekly", "type": "timeseries" }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "available_vms_windows", "type": "table" },
    { "target": "active_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "VMs Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "vms_created_weekly", "type": "timeseries" }
   ]
  },
  {
   "title": "Compute Hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "compute_hours_monthly", "type": "timeseries" }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "available_vms_windows", "type": "table" },
    { "target": "active_vms_windows", "type": "table" }
   ]
  },
  {
   "title": "VMs Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "vms_created_monthly", "type": "timeseries" }
   ]
  },
  {
   "title": "Daily",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    { "target": "daily_stats", "type": "table" }
   ]
  },
  {
   "title": "Weekly",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    { "target": "weekly_stats", "type": "table" }
   ]
  },
  {
   "title": "Monthly",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    { "target": "monthly_stats", "type": "table" }
   ]
  },
  {
   "title": "Daily Compute Hours by OS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "compute_hours_by_os", "type": "timeseries" }
   ]
  },
  {
   "title": "Daily Compute Hours by Xen Host",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "compute_hours_by_xen_host", "type": "timeseries" }
   ]
  },
  {
   "title": "Links",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "[Visit the wiki to learn how to create your own dashboard](https://hub.internal.couchbase.com/confluence/display/QA/Dynamic+VMs+Usage)\n"
   }
  }
 ]
}