{
 "title": "Static Pool VMs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Available VMs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "available_vms", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "VMs Available Now",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "total_available_vms" }
   ]
  },
  {
   "title": "Busy VMs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "busy_vms", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "VMs Busy Now",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "total_busy_vms" }
   ]
  },
  {
   "title": "Available VMs by Pool and Operating System",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "available_vms_by_os_and_pool", "legendFormat": "{{pool}}-{{os}}" }
   ]
  },
  {
   "title": "Pools",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "available_vms", "legendFormat": "{{pool}}" },
    { "expr": "busy_vms", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "available_vms_by_os", "legendFormat": "{{os}}" },
    { "expr": "busy_vms_by_os", "legendFormat": "{{os}}" }
   ]
  },
  {
   "title": "Hourly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_states", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_states", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Weekly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_states", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Monthly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_states", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Available VMs By OS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "available_vms_by_os", "legendFormat": "{{os}}" }
   ]
  },
  {
   "title": "Busy VMs By OS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "busy_vms_by_os", "legendFormat": "{{os}}" }
   ]
  },
  {
   "title": "VMs by State and Pool",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    { "expr": "vms_by_state_and_pool", "legendFormat": "{{state}}-{{pool}}" }
   ]
  },
  {
   "title": "VMs by State and Operating System",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    { "expr": "vms_by_state_and_os", "legendFormat": "{{state}}-{{os}}" }
   ]
  }
 ]
}